//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use trident_fuzz::fuzzing::*;
use trident_fuzz::fuzzing::borsh::{BorshDeserialize, BorshSerialize};

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: merkle_distributor_fee_task
// ----------------------------------------------------------------------------
pub mod merkle_distributor_fee_task {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for merkle_distributor_fee_task
    pub fn program_id() -> Pubkey {
        pubkey!("Ah7iuugan983ymZAKJAFAdvPN3My7ESkGUARrFTn3iqM")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: ClaimLocked
    // ....................................................................

    /// Main instruction struct for ClaimLocked
    pub struct ClaimLockedInstruction {
        pub accounts: ClaimLockedInstructionAccountMetas,
        pub data: ClaimLockedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimLocked instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimLockedInstructionAccountMetas {
        pub distributor: AccountMeta,

        pub claim_status: AccountMeta,

        pub from: AccountMeta,

        pub to: AccountMeta,

        pub claimant: AccountMeta,

        pub token_program: AccountMeta,

        pub fee_config: AccountMeta,

        pub fee_recipient: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for ClaimLocked instruction
    #[derive(Debug, Clone)]
    pub struct ClaimLockedInstructionAccounts {
        pub distributor: Pubkey,

        pub claim_status: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub claimant: Pubkey,

        pub fee_config: Pubkey,

        pub fee_recipient: Pubkey,
    }

    impl ClaimLockedInstructionAccounts {
        pub fn new(
            distributor: Pubkey,

            claim_status: Pubkey,

            from: Pubkey,

            to: Pubkey,

            claimant: Pubkey,

            fee_config: Pubkey,

            fee_recipient: Pubkey,
        ) -> Self {
            Self {
                distributor,

                claim_status,

                from,

                to,

                claimant,

                fee_config,

                fee_recipient,
            }
        }
    }

    /// Instruction data for ClaimLocked
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimLockedInstructionData {}

    impl ClaimLockedInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimLockedInstruction
    impl ClaimLockedInstruction {
        fn discriminator() -> [u8; 8] {
            [34u8, 206u8, 181u8, 23u8, 11u8, 207u8, 147u8, 90u8]
        }

        pub fn data(data: ClaimLockedInstructionData) -> Self {
            Self {
                accounts: ClaimLockedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimLockedInstructionAccounts) -> Self {
            self.accounts.distributor = AccountMeta::new(accounts.distributor, false);

            self.accounts.claim_status = AccountMeta::new(accounts.claim_status, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.claimant = AccountMeta::new(accounts.claimant, true);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.fee_config = AccountMeta::new_readonly(accounts.fee_config, false);

            self.accounts.fee_recipient = AccountMeta::new(accounts.fee_recipient, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.distributor.clone());

            metas.push(self.accounts.claim_status.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.claimant.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.fee_config.clone());

            metas.push(self.accounts.fee_recipient.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Clawback
    // ....................................................................

    /// Main instruction struct for Clawback
    pub struct ClawbackInstruction {
        pub accounts: ClawbackInstructionAccountMetas,
        pub data: ClawbackInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Clawback instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClawbackInstructionAccountMetas {
        pub distributor: AccountMeta,

        pub from: AccountMeta,

        pub to: AccountMeta,

        pub claimant: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Clawback instruction
    #[derive(Debug, Clone)]
    pub struct ClawbackInstructionAccounts {
        pub distributor: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub claimant: Pubkey,
    }

    impl ClawbackInstructionAccounts {
        pub fn new(distributor: Pubkey, from: Pubkey, to: Pubkey, claimant: Pubkey) -> Self {
            Self {
                distributor,

                from,

                to,

                claimant,
            }
        }
    }

    /// Instruction data for Clawback
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClawbackInstructionData {}

    impl ClawbackInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClawbackInstruction
    impl ClawbackInstruction {
        fn discriminator() -> [u8; 8] {
            [111u8, 92u8, 142u8, 79u8, 33u8, 234u8, 82u8, 27u8]
        }

        pub fn data(data: ClawbackInstructionData) -> Self {
            Self {
                accounts: ClawbackInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClawbackInstructionAccounts) -> Self {
            self.accounts.distributor = AccountMeta::new(accounts.distributor, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.claimant = AccountMeta::new_readonly(accounts.claimant, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.distributor.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.claimant.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeFeeConfig
    // ....................................................................

    /// Main instruction struct for InitializeFeeConfig
    pub struct InitializeFeeConfigInstruction {
        pub accounts: InitializeFeeConfigInstructionAccountMetas,
        pub data: InitializeFeeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeFeeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeFeeConfigInstructionAccountMetas {
        pub fee_config: AccountMeta,

        pub admin: AccountMeta,

        pub fee_recipient: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeFeeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeFeeConfigInstructionAccounts {
        pub fee_config: Pubkey,

        pub admin: Pubkey,

        pub fee_recipient: Pubkey,
    }

    impl InitializeFeeConfigInstructionAccounts {
        pub fn new(fee_config: Pubkey, admin: Pubkey, fee_recipient: Pubkey) -> Self {
            Self {
                fee_config,

                admin,

                fee_recipient,
            }
        }
    }

    /// Instruction data for InitializeFeeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeFeeConfigInstructionData {
        pub claim_fee: u64,
    }

    impl InitializeFeeConfigInstructionData {
        pub fn new(claim_fee: u64) -> Self {
            Self { claim_fee }
        }
    }

    /// Implementation for InitializeFeeConfigInstruction
    impl InitializeFeeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [62u8, 162u8, 20u8, 133u8, 121u8, 65u8, 145u8, 27u8]
        }

        pub fn data(data: InitializeFeeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeFeeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeFeeConfigInstructionAccounts) -> Self {
            self.accounts.fee_config = AccountMeta::new(accounts.fee_config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.fee_recipient = AccountMeta::new_readonly(accounts.fee_recipient, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.fee_config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.fee_recipient.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: NewClaim
    // ....................................................................

    /// Main instruction struct for NewClaim
    pub struct NewClaimInstruction {
        pub accounts: NewClaimInstructionAccountMetas,
        pub data: NewClaimInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for NewClaim instruction
    #[derive(Debug, Clone, Default)]
    pub struct NewClaimInstructionAccountMetas {
        pub distributor: AccountMeta,

        pub claim_status: AccountMeta,

        pub from: AccountMeta,

        pub to: AccountMeta,

        pub claimant: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub fee_config: AccountMeta,

        pub fee_recipient: AccountMeta,
    }

    /// Account pubkeys for NewClaim instruction
    #[derive(Debug, Clone)]
    pub struct NewClaimInstructionAccounts {
        pub distributor: Pubkey,

        pub claim_status: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub claimant: Pubkey,

        pub fee_config: Pubkey,

        pub fee_recipient: Pubkey,
    }

    impl NewClaimInstructionAccounts {
        pub fn new(
            distributor: Pubkey,

            claim_status: Pubkey,

            from: Pubkey,

            to: Pubkey,

            claimant: Pubkey,

            fee_config: Pubkey,

            fee_recipient: Pubkey,
        ) -> Self {
            Self {
                distributor,

                claim_status,

                from,

                to,

                claimant,

                fee_config,

                fee_recipient,
            }
        }
    }

    /// Instruction data for NewClaim
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct NewClaimInstructionData {
        pub amount_unlocked: u64,

        pub amount_locked: u64,

        pub proof: Vec<[u8; 32]>,
    }

    impl NewClaimInstructionData {
        pub fn new(amount_unlocked: u64, amount_locked: u64, proof: Vec<[u8; 32]>) -> Self {
            Self {
                amount_unlocked,

                amount_locked,

                proof,
            }
        }
    }

    /// Implementation for NewClaimInstruction
    impl NewClaimInstruction {
        fn discriminator() -> [u8; 8] {
            [78u8, 177u8, 98u8, 123u8, 210u8, 21u8, 187u8, 83u8]
        }

        pub fn data(data: NewClaimInstructionData) -> Self {
            Self {
                accounts: NewClaimInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: NewClaimInstructionAccounts) -> Self {
            self.accounts.distributor = AccountMeta::new(accounts.distributor, false);

            self.accounts.claim_status = AccountMeta::new(accounts.claim_status, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.claimant = AccountMeta::new(accounts.claimant, true);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.fee_config = AccountMeta::new_readonly(accounts.fee_config, false);

            self.accounts.fee_recipient = AccountMeta::new(accounts.fee_recipient, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.distributor.clone());

            metas.push(self.accounts.claim_status.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.claimant.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.fee_config.clone());

            metas.push(self.accounts.fee_recipient.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: NewDistributor
    // ....................................................................

    /// Main instruction struct for NewDistributor
    pub struct NewDistributorInstruction {
        pub accounts: NewDistributorInstructionAccountMetas,
        pub data: NewDistributorInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for NewDistributor instruction
    #[derive(Debug, Clone, Default)]
    pub struct NewDistributorInstructionAccountMetas {
        pub distributor: AccountMeta,

        pub clawback_receiver: AccountMeta,

        pub mint: AccountMeta,

        pub token_vault: AccountMeta,

        pub admin: AccountMeta,

        pub system_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for NewDistributor instruction
    #[derive(Debug, Clone)]
    pub struct NewDistributorInstructionAccounts {
        pub distributor: Pubkey,

        pub clawback_receiver: Pubkey,

        pub mint: Pubkey,

        pub token_vault: Pubkey,

        pub admin: Pubkey,
    }

    impl NewDistributorInstructionAccounts {
        pub fn new(
            distributor: Pubkey,

            clawback_receiver: Pubkey,

            mint: Pubkey,

            token_vault: Pubkey,

            admin: Pubkey,
        ) -> Self {
            Self {
                distributor,

                clawback_receiver,

                mint,

                token_vault,

                admin,
            }
        }
    }

    /// Instruction data for NewDistributor
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct NewDistributorInstructionData {
        pub version: u64,

        pub root: [u8; 32],

        pub max_total_claim: u64,

        pub max_num_nodes: u64,

        pub start_vesting_ts: i64,

        pub end_vesting_ts: i64,

        pub clawback_start_ts: i64,
    }

    impl NewDistributorInstructionData {
        pub fn new(
            version: u64,

            root: [u8; 32],

            max_total_claim: u64,

            max_num_nodes: u64,

            start_vesting_ts: i64,

            end_vesting_ts: i64,

            clawback_start_ts: i64,
        ) -> Self {
            Self {
                version,

                root,

                max_total_claim,

                max_num_nodes,

                start_vesting_ts,

                end_vesting_ts,

                clawback_start_ts,
            }
        }
    }

    /// Implementation for NewDistributorInstruction
    impl NewDistributorInstruction {
        fn discriminator() -> [u8; 8] {
            [32u8, 139u8, 112u8, 171u8, 0u8, 2u8, 225u8, 155u8]
        }

        pub fn data(data: NewDistributorInstructionData) -> Self {
            Self {
                accounts: NewDistributorInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: NewDistributorInstructionAccounts) -> Self {
            self.accounts.distributor = AccountMeta::new(accounts.distributor, false);

            self.accounts.clawback_receiver = AccountMeta::new(accounts.clawback_receiver, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_vault = AccountMeta::new(accounts.token_vault, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.distributor.clone());

            metas.push(self.accounts.clawback_receiver.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_vault.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetAdmin
    // ....................................................................

    /// Main instruction struct for SetAdmin
    pub struct SetAdminInstruction {
        pub accounts: SetAdminInstructionAccountMetas,
        pub data: SetAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetAdminInstructionAccountMetas {
        pub distributor: AccountMeta,

        pub admin: AccountMeta,

        pub new_admin: AccountMeta,
    }

    /// Account pubkeys for SetAdmin instruction
    #[derive(Debug, Clone)]
    pub struct SetAdminInstructionAccounts {
        pub distributor: Pubkey,

        pub admin: Pubkey,

        pub new_admin: Pubkey,
    }

    impl SetAdminInstructionAccounts {
        pub fn new(distributor: Pubkey, admin: Pubkey, new_admin: Pubkey) -> Self {
            Self {
                distributor,

                admin,

                new_admin,
            }
        }
    }

    /// Instruction data for SetAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetAdminInstructionData {}

    impl SetAdminInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SetAdminInstruction
    impl SetAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [251u8, 163u8, 0u8, 52u8, 91u8, 194u8, 187u8, 92u8]
        }

        pub fn data(data: SetAdminInstructionData) -> Self {
            Self {
                accounts: SetAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetAdminInstructionAccounts) -> Self {
            self.accounts.distributor = AccountMeta::new(accounts.distributor, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.new_admin = AccountMeta::new_readonly(accounts.new_admin, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.distributor.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.new_admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetClaimFee
    // ....................................................................

    /// Main instruction struct for SetClaimFee
    pub struct SetClaimFeeInstruction {
        pub accounts: SetClaimFeeInstructionAccountMetas,
        pub data: SetClaimFeeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetClaimFee instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetClaimFeeInstructionAccountMetas {
        pub fee_config: AccountMeta,

        pub admin: AccountMeta,

        pub new_fee_recipient: AccountMeta,
    }

    /// Account pubkeys for SetClaimFee instruction
    #[derive(Debug, Clone)]
    pub struct SetClaimFeeInstructionAccounts {
        pub fee_config: Pubkey,

        pub admin: Pubkey,

        pub new_fee_recipient: Pubkey,
    }

    impl SetClaimFeeInstructionAccounts {
        pub fn new(fee_config: Pubkey, admin: Pubkey, new_fee_recipient: Pubkey) -> Self {
            Self {
                fee_config,

                admin,

                new_fee_recipient,
            }
        }
    }

    /// Instruction data for SetClaimFee
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetClaimFeeInstructionData {
        pub claim_fee: u64,
    }

    impl SetClaimFeeInstructionData {
        pub fn new(claim_fee: u64) -> Self {
            Self { claim_fee }
        }
    }

    /// Implementation for SetClaimFeeInstruction
    impl SetClaimFeeInstruction {
        fn discriminator() -> [u8; 8] {
            [124u8, 3u8, 184u8, 17u8, 133u8, 67u8, 255u8, 50u8]
        }

        pub fn data(data: SetClaimFeeInstructionData) -> Self {
            Self {
                accounts: SetClaimFeeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetClaimFeeInstructionAccounts) -> Self {
            self.accounts.fee_config = AccountMeta::new(accounts.fee_config, false);

            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.new_fee_recipient =
                AccountMeta::new_readonly(accounts.new_fee_recipient, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.fee_config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.new_fee_recipient.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetClawbackReceiver
    // ....................................................................

    /// Main instruction struct for SetClawbackReceiver
    pub struct SetClawbackReceiverInstruction {
        pub accounts: SetClawbackReceiverInstructionAccountMetas,
        pub data: SetClawbackReceiverInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetClawbackReceiver instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetClawbackReceiverInstructionAccountMetas {
        pub distributor: AccountMeta,

        pub new_clawback_account: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for SetClawbackReceiver instruction
    #[derive(Debug, Clone)]
    pub struct SetClawbackReceiverInstructionAccounts {
        pub distributor: Pubkey,

        pub new_clawback_account: Pubkey,

        pub admin: Pubkey,
    }

    impl SetClawbackReceiverInstructionAccounts {
        pub fn new(distributor: Pubkey, new_clawback_account: Pubkey, admin: Pubkey) -> Self {
            Self {
                distributor,

                new_clawback_account,

                admin,
            }
        }
    }

    /// Instruction data for SetClawbackReceiver
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetClawbackReceiverInstructionData {}

    impl SetClawbackReceiverInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SetClawbackReceiverInstruction
    impl SetClawbackReceiverInstruction {
        fn discriminator() -> [u8; 8] {
            [153u8, 217u8, 34u8, 20u8, 19u8, 29u8, 229u8, 75u8]
        }

        pub fn data(data: SetClawbackReceiverInstructionData) -> Self {
            Self {
                accounts: SetClawbackReceiverInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetClawbackReceiverInstructionAccounts) -> Self {
            self.accounts.distributor = AccountMeta::new(accounts.distributor, false);

            self.accounts.new_clawback_account =
                AccountMeta::new_readonly(accounts.new_clawback_account, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.distributor.clone());

            metas.push(self.accounts.new_clawback_account.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: ClaimStatus
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ClaimStatus {
    pub claimant: Pubkey,

    pub locked_amount: u64,

    pub locked_amount_withdrawn: u64,

    pub unlocked_amount: u64,

    pub fee_paid: bool,
}

impl ClaimStatus {
    pub fn new(
        claimant: Pubkey,

        locked_amount: u64,

        locked_amount_withdrawn: u64,

        unlocked_amount: u64,

        fee_paid: bool,
    ) -> Self {
        Self {
            claimant,

            locked_amount,

            locked_amount_withdrawn,

            unlocked_amount,

            fee_paid,
        }
    }
}

/// Custom struct: ClaimedEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ClaimedEvent {
    pub claimant: Pubkey,

    pub amount: u64,
}

impl ClaimedEvent {
    pub fn new(claimant: Pubkey, amount: u64) -> Self {
        Self { claimant, amount }
    }
}

/// Custom struct: FeeCollectedEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FeeCollectedEvent {
    pub claimant: Pubkey,

    pub fee_amount: u64,

    pub fee_recipient: Pubkey,

    pub distributor: Pubkey,
}

impl FeeCollectedEvent {
    pub fn new(
        claimant: Pubkey,

        fee_amount: u64,

        fee_recipient: Pubkey,

        distributor: Pubkey,
    ) -> Self {
        Self {
            claimant,

            fee_amount,

            fee_recipient,

            distributor,
        }
    }
}

/// Custom struct: FeeConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FeeConfig {
    pub admin: Pubkey,

    pub claim_fee: u64,

    pub fee_recipient: Pubkey,

    pub bump: u8,
}

impl FeeConfig {
    pub fn new(admin: Pubkey, claim_fee: u64, fee_recipient: Pubkey, bump: u8) -> Self {
        Self {
            admin,

            claim_fee,

            fee_recipient,

            bump,
        }
    }
}

/// Custom struct: MerkleDistributor
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MerkleDistributor {
    pub bump: u8,

    pub version: u64,

    pub root: [u8; 32],

    pub mint: Pubkey,

    pub token_vault: Pubkey,

    pub max_total_claim: u64,

    pub max_num_nodes: u64,

    pub total_amount_claimed: u64,

    pub num_nodes_claimed: u64,

    pub start_ts: i64,

    pub end_ts: i64,

    pub clawback_start_ts: i64,

    pub clawback_receiver: Pubkey,

    pub admin: Pubkey,

    pub clawed_back: bool,
}

impl MerkleDistributor {
    pub fn new(
        bump: u8,

        version: u64,

        root: [u8; 32],

        mint: Pubkey,

        token_vault: Pubkey,

        max_total_claim: u64,

        max_num_nodes: u64,

        total_amount_claimed: u64,

        num_nodes_claimed: u64,

        start_ts: i64,

        end_ts: i64,

        clawback_start_ts: i64,

        clawback_receiver: Pubkey,

        admin: Pubkey,

        clawed_back: bool,
    ) -> Self {
        Self {
            bump,

            version,

            root,

            mint,

            token_vault,

            max_total_claim,

            max_num_nodes,

            total_amount_claimed,

            num_nodes_claimed,

            start_ts,

            end_ts,

            clawback_start_ts,

            clawback_receiver,

            admin,

            clawed_back,
        }
    }
}

/// Custom struct: NewClaimEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct NewClaimEvent {
    pub claimant: Pubkey,

    pub timestamp: i64,
}

impl NewClaimEvent {
    pub fn new(claimant: Pubkey, timestamp: i64) -> Self {
        Self {
            claimant,

            timestamp,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
